name: CornmanServices
favicon: null
layout_spectrum: 0.21494149533100426
typography_spectrum: 0.6705102866981179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.13765437435358763
  lightness: 0.45692993560805917
  saturation: 0.4186497675254941
  rhythmicContrast: 0.9386249617673457
purpose: []
